---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    hostname: plex
    network_mode: host
    environment:
      - PUID=2000
      - PGID=1000
      - VERSION=latest
      - DOCKER_MODS=linuxserver/mods:plex-absolute-hama
    volumes:
      - /var/mediabox/plex/library:/config
      - /var/mediabox/plex/tv:/tv
      - /var/mediabox/plex/movies:/movies
      - /var/mediabox/bittorrent/Downloads:/downloads
    restart: unless-stopped

